package net.joarchitectus.client.datos.dominio;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", uniqueConstraints
        = {
            @UniqueConstraint(columnNames = "correo_electronico"),
            @UniqueConstraint(columnNames = "documento")
        })
public class Usuarios extends EntidadPerpetua{

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "gen_usuario")
    @SequenceGenerator(name = "gen_usuario", sequenceName = "usuario_id_seq")
    private Long id;
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "rol", nullable = false)
    private Rol rol;
    @Column(name = "documento", nullable = false, length = 50)
    private String documento;
    @Column(name = "clave", nullable = false, length = 100)
    private String clave;
    @Column(name = "nombres", nullable = false, length = 150)
    private String nombres;
    @Column(name = "apellidos", nullable = false, length = 150)
    private String apellidos;

    //0001707: correo electrónico debe ser opcional al crear usuarios
    @Column(name = "correo_electronico", unique = true, length = 150)
    private String correoElectronico;
    @Column(name = "telefono_oficina", length = 25)
    private String telefonoOficina;
    @Column(name = "telefono_domicilio", length = 25)
    private String telefonoDomicilio;
    @Column(name = "telefono_celular", length = 25)
    private String telefonoCelular;
    @Column(name = "llave_cambio_clave", length = 50)
    private String llaveCambioClave;
//    @Temporal(TemporalType.TIMESTAMP)
//    @Column(name = "fecha_inactivado", length = 29)
//    private Date fechaInactivado;
    @Column(name = "inactivo", nullable = true)
    private Boolean inactivo;
//    @Column(name = "foto")
//    private byte[] foto;
//    @Column(name = "content_type_foto")
//    private String contentTypeFoto;
    @Column(name = "latch_accounid", length = 200)
    private String latchAccountid;
    @Column(name = "latch_token", length = 200)
    private String latchToken;
    @Column(name = "token_auth", length = 200)
    private String tokenAuth;

    /**
     * Setea en nulo los atributos del objeto. este método se invoca para anular
     * la sesión del usuario
     */
    public void resetear() {
        this.id = null;
        this.rol = null;
        this.documento = null;
        this.clave = null;
        this.nombres = null;
        this.apellidos = null;
        this.correoElectronico = null;
        this.telefonoOficina = null;
        this.telefonoOficina = null;
        this.llaveCambioClave = null;
        this.fechaInactivado = null;
//        this.foto = null;
//        this.contentTypeFoto = null;
        this.clave = null;
    }

    public String crearNombreCompleto() {
        return nombres + " " + apellidos;
    }

    public Usuarios() {
    }

    public Usuarios(Long id, Rol rol, String documento, String clave, String nombres, String apellidos, String correoElectronico) {
        this.id = id;
        this.rol = rol;
        this.documento = documento;
        this.clave = clave;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.correoElectronico = correoElectronico;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    public Rol getRol() {
        return this.rol;
    }

    public void setRol(Rol rol) {
        this.rol = rol;
    }

    public String getDocumento() {
        return this.documento;
    }

    public void setDocumento(String documento) {
        this.documento = documento;
    }

    @JsonIgnore
    public String getClave() {
        return this.clave;
    }

    public void setClave(String clave) {
        this.clave = clave;
    }

//    @JsonIgnore(true)
//    public byte[] getFoto() {
//        return foto;
//    }
//
//    public void setFoto(byte[] foto) {
//        this.foto = foto;
//    }
//
//    public String getContentTypeFoto() {
//        return contentTypeFoto;
//    }
//
//    public void setContentTypeFoto(String contentTypeFoto) {
//        this.contentTypeFoto = contentTypeFoto;
//    }

    public String getNombres() {
        return this.nombres;
    }

    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    public String getApellidos() {
        return this.apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    @Transient
    public String getNombreCompleto() {
        return getNombres() + " " + getApellidos();
    }

    public String getCorreoElectronico() {
        return this.correoElectronico;
    }

    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }

    public String getTelefonoOficina() {
        return this.telefonoOficina;
    }

    public void setTelefonoOficina(String telefonoOficina) {
        this.telefonoOficina = telefonoOficina;
    }

    public String getTelefonoDomicilio() {
        return telefonoDomicilio;
    }

    public void setTelefonoDomicilio(String telefonoDomicilio) {
        this.telefonoDomicilio = telefonoDomicilio;
    }

    public String getTelefonoCelular() {
        return this.telefonoCelular;
    }

    public void setTelefonoCelular(String telefonoCelular) {
        this.telefonoCelular = telefonoCelular;
    }

    @Transient
    public boolean isAdministradorSistema() {
        return this.getRol().getId() == Rol.ROL_ADMINISTRADOR_SISTEMA;
    }

    @Transient
    public boolean isAdminEmpresa() {
        return this.getRol().getId() == Rol.ROL_ADMINISTRADOR_EMPRESA;
    }

    public String getLlaveCambioClave() {
        return this.llaveCambioClave;
    }

    public void setLlaveCambioClave(String llaveCambioClave) {
        this.llaveCambioClave = llaveCambioClave;
    }

//        public Date getFechaInactivado() {
//        return this.fechaInactivado;
//    }
//
//    public void setFechaInactivado(Date fechaInactivado) {
//        this.fechaInactivado = fechaInactivado;
//    }
    public Boolean getInactivo() {
        return inactivo;
    }

    public void setInactivo(Boolean inactivo) {
        this.inactivo = inactivo;
    }

    public String getLatchAccountid() {
        return latchAccountid;
    }

    public void setLatchAccountid(String latchAccountid) {
        this.latchAccountid = latchAccountid;
    }

    @JsonIgnore
    public String getLatchToken() {
        return latchToken;
    }

    public void setLatchToken(String latchToken) {
        this.latchToken = latchToken;
    }

    @JsonIgnore
    public String getTokenAuth() {
        return tokenAuth;
    }

    public void setTokenAuth(String tokenAuth) {
        this.tokenAuth = tokenAuth;
    }
    
    
    /**
     * Copiar los datos de un objeto a otro
     * @param usuario 
     */
    public void copiarDatos(Usuarios usuario) {
        this.id = usuario.getId();
        this.rol = usuario.getRol();
        this.documento = usuario.getDocumento();
        this.clave = usuario.getClave();
        this.nombres = usuario.getNombres();
        this.apellidos = usuario.getApellidos();
        this.correoElectronico = usuario.getCorreoElectronico();
        this.telefonoOficina = usuario.getTelefonoOficina();
        this.telefonoCelular = usuario.getTelefonoCelular();
        this.llaveCambioClave = usuario.getLlaveCambioClave();
        this.fechaInactivado = usuario.getFechaInactivado();
        this.latchAccountid = usuario.getLatchAccountid();
        this.latchToken = usuario.getLatchToken();
        this.tokenAuth = usuario.getTokenAuth();
    }

    @Override
    public String toString() {
        return getLabel();
    }

    @Transient
    @Override
    public String getLabel() {
        return getNombreCompleto();
    }

}
